### ISSUE TITLE
Gebruik van ''var'' in je javascript.

### ISSUE THREAD

**Issue by TygoWolven** [Seijno/the-startup-responsive-interactieve-website#11]
In je javascript zie ik dat je veel gebruik maakt van de ''var''.  Tegenwoordig word de ''var'' vrijwel nooit meer gebruikt vanwege verschillende redenen. De makkelijkste reden is omdat ''let'' en ''const'' veel beter zijn dan de var. 

https://github.com/Seijno/the-startup-responsive-interactieve-website/blob/3c22e281ed3ce2438e9b4a6cf181b522a903dcd1/script.js#L1-L8

Dit kan je simpel oplossen door alles te veranderen in een ''const'' zoals je hier beneden kan zien. Let op dat je komma's gebruikt totdat je de const wilt sluiten, anders werkt de code niet.

<img width="600" src="https://github.com/Seijno/the-startup-responsive-interactieve-website/assets/144010858/929eea9d-d1bd-467e-8f8d-f7724d8ae887">

Mocht je de precies willen weten wat de redenen zijn waarom er geen ''var'' meer wordt gebruikt heb ik hier nog een artikel waarin uitgebreid het verschil word uitgelegd tussen deze selectoren.
https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

<img width="600" src="https://github.com/Seijno/the-startup-responsive-interactieve-website/assets/144010858/7bed8169-ba65-4183-a91b-b89f2ba26ce9">

**Comment by Seijno** [comment]
ik heb enorm van jou geleerd, dankjewel!
