### ISSUE TITLE
nav-bar

### ISSUE THREAD

**Issue by lemuelmgsn** [Seijno/the-startup-responsive-interactieve-website#2]
https://github.com/Seijno/the-startup-responsive-interactieve-website/blob/d192bb49b2c804270e839ef7e4c274abd4d997cc/index.html#L10-L20

ik denk dat je hier beter nav kunt gebruiken inplaats van een header. 
of de nav in je header

**Comment by Seijno** [comment]
Ik heb er nog eens naar gekeken maar dit is een bewuste keuze, dit komt omdat ik de nav tag gebruik voor het filter systeem. Eventueel had nav in header gekunt maar dat lijkt mij dubbel.
