### ISSUE TITLE
Buttons in ul staan niet helemaal netjes

### ISSUE THREAD

**Issue by zoepje** [Seijno/the-startup-responsive-interactieve-website#8]
https://github.com/Seijno/the-startup-responsive-interactieve-website/blob/21b9bd0a527681bb2d95557b351bc72848bf7bf8/index.html#L23-L25

Je hebt een `ul` aangemaakt waarin je `buttons` heb gezet die niet in een `li`  zitten dit is niet helemaal netjes. Probeer de `button` in een `li` te zetten.

Je kunt meer over `ul` hier lezen https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

**Comment by Seijno** [comment]
fixed
