### ISSUE TITLE
Image width en height unit klopt niet helemaal

### ISSUE THREAD

**Issue by zoepje** [Seijno/the-startup-responsive-interactieve-website#9]
https://github.com/Seijno/the-startup-responsive-interactieve-website/blob/21b9bd0a527681bb2d95557b351bc72848bf7bf8/index.html#L32-L33

Je gebruikt `width=300px` en `height=300px` om je image op te maken. Voor `width` en `height` neemt hij automatisch pixels en mag je geen units gebruiken.

Je kunt hier meer lezen over image width/height https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#width

**Comment by Seijno** [comment]
#9 px is weggehaald waardoor de issue is verholpen
